#######################################################################
# WARNING: This file automatically generated by Borg on <%=Date.create().format('{yyyy}-{MM}-{dd} {HH}:{mm}:{ss} {tz}')%>
#          If you need to edit this file, do so in the Borg repository.
#          Any change you make here WILL be overridden on assimilation.
#######################################################################

<% for key, o of @paths: %>
<%=key%> {
<% for k, v of o: %>
  <%=k%><%=if v is true then '' else ' '+v%>
<% end %>
}
<% end %>
